### ISSUE TITLE
Other Stata String Distance packages

### ISSUE THREAD

**Issue by wbuchanan** [luispfonseca/stata-rcallstringdist#1]
https://github.com/wbuchanan/StataStringUtilities

There’s been a Stata package for string distance for a few years now that also includes a broader variety of phonetic encoding algorithms as well.  It all uses the Java API, but figured you might want to know about this.

**Comment by luispfonseca** [comment]
Thanks for bringing this to my attention. I've added a mention to the readme file so people can look up your package as well.
